### PR TITLE
Fix pubkey validation

### LINKED ISSUE #10: Support for non RSA keys
From: https://github.com/hashbang/hashbang.sh/issues/24

### PR DESCRIPTION
**Pull request by mwgamera**
* Actually allow ECDSA keys on NIST curves (previously wrong identifier `ssh-ecdsa` was used instead of the three `ecdsa-sha2-nistp*`)
* Also allow Ed25519 keys while we're at it.
* Remove check for minimal length that filtered Ed25519 out (leave check for maximal length in place to prevent DoS as b34f452 intended when adding these checks).

It might fix #10.

### CODE REVIEW

**Comment by lrvick** [comment]
ed25519 keys, with no comment, should be a minimum of 81 chars long. 

Having the minimum helps at least immediately filter out obviously invalid keys. (People often end up pasting a newline after the key type). I would prefer we still account for this and throw away obviously invalid keys in the process.

Otherwise looks good.

**Comment by mwgamera** [comment]
Actually, Ed25519 must have exactly 80 characters (ignoring the commends and space separating them from the key). If I'm not mistaken, all the key types except RSA have fixed length, so maybe I should add a short dict with lengths there and check them after split? Well, there's already base64 decoding in place and I think it will croak if padding is incorrect (1 chance in 4 when randomly truncated).

**Comment by mwgamera** [comment]
Upon closer inspection, trying to do more detailed checks without fully parsing the keys would be needlessly complex. So I just restored the original check but adjusted it to 80 as no valid key of any type can ever be shorter in encoded form.

**Comment by cnicolov** [comment]
I think 
   if value[0] not in ('ssh-rsa','ssh-dsa','ssh-ecdsa'):

Does not recognize:
ssh-dss AAAAB3NzaC1kc3MAAACBAPv7OJuB7om/8cFk87LyL3pzRFScQ...blablabla

And returns true. I've tested with FreeBSD 10.1, Ubuntu 14.10 and CentOS 6.5 keys. 
 (Via hashbangctl)

**Comment by mwgamera** [comment]
Yes, I noticed that too, and I believe this is exactly what c2aad31 fixes. Or did I miss something? It seems that diff of #14 is identical to it.
Anyway, OpenSSH uses here the same names as SSH protocol uses on wire, so, possibly except for some experimental types, they should be on the list of registered names which is [maintained by IANA](https://www.iana.org/assignments/ssh-parameters/ssh-parameters.xhtml#ssh-parameters-19) and names like `ssh-ecdsa` or `ssh-dsa` should never happen. Although, I can see that two hashbang users actually got around the faulty verification by changing these tags before base64 encoded part ;)

**Comment by cnicolov** [comment]
The same check exists in many other scripts as: [provisor-create](https://github.com/hashbang/provisor/blob/master/bin/provisor-create#L49) . Maybe it needs a little more attention.

**Comment by mwgamera** [comment]
In shell script it IMO be better to directly use `ssh-keygen` command to check if it recognizes it as a valid key, unless there is any reason to blacklist some valid types, of course. But anyway, I don't know how is that script intended to be used. As I see it also contains username validation, but IIUC automatic registration uses the python module. Perhaps it's a good idea to unify all that so it's done only in one place?

**Comment by lrvick** [comment]
provisor-create is legacy leftover at this point, as we have fully switched to the ldap library.

This fix seems to cover the core problem. Merging.

**Pull request merged**
